  [build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"