

  [build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[context.production]
  environment = { NODE_ENV = "production" }

[build.environment]
  PARCEL_CACHE = ".cache"